### ISSUE TITLE
website is down for some times

### ISSUE THREAD

**Issue by SiRumCz** [AuthEceSoftEng/npm-miner#6]
Hi,

I have been following your npm-miner project for few month now. Since I am trying to study the health of npm software ecosystem, your project inspired and helped me getting npm data. But recently I found out your npm-miner.com is down. This is the error message I am getting:
```
TypeError: Cannot read property 'topTenStars' of null
```
Please let me know whether you are still maintaining this website, or you have already moved to other projects.
Thanks,
Kevin(Zhe) Chen

**Comment by kyrcha** [comment]
Hi @SiRumCz 

Thank you for your interest in npm-miner. We had a security issue recently but we are still maintaining it. Probably we will have to restart crawling. We will let you know as soon as it comes up.

**Comment by kyrcha** [comment]
npm-miner is up again, a new crawl has started (so it is kind of empty at the moment) but it is more robust and new features will come soon.

**Comment by SiRumCz** [comment]
Thank you for the update!
